/* Site configuration, app facts and all page texts (en / de / bs). */

export const SITE = {
  baseUrl: 'https://metur100.github.io/Islam.Apps.Landing/',
  owner: 'Medin Turkes',
  brand: 'Certi Development',
  email: 'medin_93@live.com',
  // Street and postcode for the Impressum, e.g. 'Musterstraße 1, 40210 Düsseldorf'. Until it is set, only the city is shown.
  address: null,
  city: 'Düsseldorf',
  updated: '2026-10-07',
  // Set to true for an app once it is live on Google Play; until then the button reads "Coming soon".
  live: { 'islam-quest': false, 'story-of-the-prophets': false, 'knowledge-rpg': false, sira: false },
};

export const LANGS = ['en', 'de', 'bs'];
export const LANG_NAMES = { en: 'English', de: 'Deutsch', bs: 'Bosanski' };
export const OG_LOCALE = { en: 'en_US', de: 'de_DE', bs: 'bs_BA' };

export const APPS = [
  {
    id: 'islam-quest',
    package: 'com.certidevelopment.islamquest',
    repo: 'Islam.Quest',
    category: 'EducationalGame',
    audience: { en: 'Children 7–14', de: 'Kinder 7–14', bs: 'Djeca 7–14' },
    tagline: {
      en: 'A playful adventure through Salah, the Quran, the prophets, Arabic and good character.',
      de: 'Ein spielerisches Abenteuer durch Gebet, Koran, Propheten, Arabisch und gutes Benehmen.',
      bs: 'Razigrana avantura kroz namaz, Kur’an, poslanike, arapski i lijepo ponašanje.',
    },
    stored: {
      en: 'your chosen name, character, learning progress and settings',
      de: 'deinen gewählten Namen, deinen Charakter, deinen Lernfortschritt und deine Einstellungen',
      bs: 'tvoje izabrano ime, lik, napredak u učenju i postavke',
    },
    network: {
      en: 'The app only uses the internet when you tap “Listen” on a Quran recitation. The audio file is then loaded from the Islamic Network CDN (cdn.islamic.network). Like every web request, this transmits your device’s IP address to that server; the app sends no other information. Everything else works offline.',
      de: 'Die App nutzt das Internet nur, wenn du bei einer Koranrezitation auf „Anhören“ tippst. Die Audiodatei wird dann vom Islamic Network CDN (cdn.islamic.network) geladen. Wie bei jeder Webanfrage wird dabei die IP-Adresse deines Geräts an diesen Server übertragen; die App sendet keine weiteren Informationen. Alles andere funktioniert offline.',
      bs: 'Aplikacija koristi internet samo kada dodirneš „Slušaj“ kod učenja Kur’ana. Audio datoteka se tada učitava s Islamic Network CDN-a (cdn.islamic.network). Kao i kod svakog web zahtjeva, pri tome se tom serveru prenosi IP adresa tvog uređaja; aplikacija ne šalje nikakve druge podatke. Sve ostalo radi bez interneta.',
    },
    reminders: true,
    children: true,
  },
  {
    id: 'story-of-the-prophets',
    package: 'com.certidevelopment.storyoftheprophets',
    repo: 'Story.Of.The.Prophets',
    category: 'EducationalGame',
    audience: { en: 'Children 6–12', de: 'Kinder 6–12', bs: 'Djeca 6–12' },
    tagline: {
      en: 'The stories of eight prophets as told in the Quran – as an interactive storybook.',
      de: 'Die Geschichten von acht Propheten, wie der Koran sie erzählt – als interaktives Bilderbuch.',
      bs: 'Priče o osam poslanika onako kako ih kazuje Kur’an – kao interaktivna slikovnica.',
    },
    stored: {
      en: 'your learning progress, review questions, badges and settings',
      de: 'deinen Lernfortschritt, deine Wiederholungsfragen, Abzeichen und Einstellungen',
      bs: 'tvoj napredak u učenju, pitanja za ponavljanje, značke i postavke',
    },
    children: true,
  },
  {
    id: 'knowledge-rpg',
    package: 'com.certidevelopment.knowledgerpg',
    repo: 'Knowledge.RPG',
    category: 'EducationalGame',
    audience: { en: 'Ages 9+', de: 'Ab 9 Jahren', bs: 'Od 9 godina' },
    tagline: {
      en: 'A learning RPG in which your hero grows only through real knowledge.',
      de: 'Ein Lern-RPG, in dem dein Held nur durch echtes Wissen wächst.',
      bs: 'RPG igra učenja u kojoj tvoj junak raste samo kroz pravo znanje.',
    },
    stored: {
      en: 'your hero (name and appearance), learning progress, quests, achievements and settings',
      de: 'deinen Helden (Name und Aussehen), deinen Lernfortschritt, Quests, Erfolge und Einstellungen',
      bs: 'tvog junaka (ime i izgled), napredak u učenju, misije, dostignuća i postavke',
    },
    children: true,
  },
  {
    id: 'sira',
    package: 'com.certidevelopment.sira',
    repo: 'Sira',
    category: 'EducationalApplication',
    audience: { en: 'Teens & adults', de: 'Jugendliche & Erwachsene', bs: 'Mladi i odrasli' },
    tagline: {
      en: 'A source-based journey through the life of the Prophet Muhammad ﷺ.',
      de: 'Eine quellenbasierte Reise durch das Leben des Propheten Muhammad ﷺ.',
      bs: 'Putovanje kroz život Poslanika Muhammeda ﷺ, zasnovano na izvorima.',
    },
    stored: {
      en: 'your progress, quiz results, bookmarks, written reflections and settings',
      de: 'deinen Fortschritt, deine Quizergebnisse, Lesezeichen, geschriebenen Reflexionen und Einstellungen',
      bs: 'tvoj napredak, rezultate kvizova, zabilješke, napisana razmišljanja i postavke',
    },
    links: true,
    reminders: true,
  },
];

/* Interface texts. */
export const UI = {
  en: {
    siteName: 'Islamic Learning Apps',
    metaDescription: 'Four free Islamic learning apps for children, teens and adults – no ads, no tracking, offline, source-based. In English, German and Bosnian.',
    nav: { apps: 'Apps', principles: 'Principles', faq: 'FAQ', contact: 'Contact' },
    heroKicker: 'Free · No ads · Offline',
    heroTitle: 'Learn Islam with joy – reliably and privately',
    heroText: 'Four free learning apps for children, teens and adults: from the first prayer and the stories of the prophets to the life of the Prophet Muhammad ﷺ. No ads, no purchases, no tracking – and every lesson names its sources.',
    heroCta: 'Discover the apps',
    appsTitle: 'The apps',
    appsText: 'Each app is made for a different age and way of learning. All of them are available in English, German and Bosnian.',
    more: 'Learn more',
    principlesTitle: 'What all four apps have in common',
    principles: [
      ['Completely free', 'No ads, no in-app purchases, no subscriptions and nothing pay-to-win.'],
      ['Private by design', 'No accounts, no analytics, no tracking. Progress stays on your device.'],
      ['Works offline', 'All content is inside the app – ideal for travel, school and family time.'],
      ['Source-based', 'Quran and hadith references for every lesson. Nothing invented; scholarly differences are noted.'],
      ['Respectful', 'Prophets are never depicted. Illustrations show only landscapes, buildings and objects.'],
      ['Accessible', 'Three languages, larger text, high contrast, reduced motion and screen-reader support.'],
    ],
    parentsTitle: 'For parents, teachers and mosque communities',
    parentsText: 'The apps are learning companions – they support family learning, Islamic religious education and weekend schools, but they do not replace parents, teachers or imams, and they do not give fatwas. Children can use the children’s apps safely: there are no ads, no chats, no links to social networks and no data collection.',
    shareTitle: 'Share the apps',
    shareText: 'The apps are free and will stay free. The best way to support them is to share this page with families, teachers and your mosque community.',
    copyLink: 'Copy link',
    copied: 'Link copied',
    faqTitle: 'Frequently asked questions',
    faq: [
      ['Are the apps really free?', 'Yes. There are no ads, no purchases and no subscriptions – now and in the future.'],
      ['Do the apps need the internet?', 'No. All four apps work offline. Only Islam Quest loads audio from the internet when you choose to listen to a Quran recitation.'],
      ['Which languages are supported?', 'English, German and Bosnian. You can switch the language at any time in the app.'],
      ['How do you make sure the content is correct?', 'Every lesson cites its sources (Quran and recognised hadith and Seerah works). Quran text comes from the verified Tanzil text and is never typed by hand. Nothing is invented, and where scholars hold different valid views, the app says so. If you find a mistake, please write to us – corrections are welcome.'],
      ['Are prophets shown in pictures?', 'No. Prophets are never depicted. People in Sira are shown only through typography.'],
      ['Which devices are supported?', 'Android phones and tablets via Google Play.'],
      ['What data do the apps collect?', 'None. Progress is stored only on your device and can be deleted in the settings at any time. See the privacy policy of each app.'],
    ],
    contactTitle: 'Contact',
    contactText: 'Questions, feedback or a correction to the content? We are happy to hear from you.',
    footerNote: 'Free Islamic learning apps by Certi Development.',
    privacy: 'Privacy policy',
    imprint: 'Imprint',
    appPrivacy: 'App privacy policy',
    language: 'Language',
    // App page
    getOnPlay: 'Get it on Google Play',
    comingSoon: 'Coming soon to Google Play',
    forWhom: 'For',
    languages: 'Languages',
    languagesValue: 'English, German, Bosnian',
    price: 'Price',
    priceValue: 'Free – no ads, no purchases',
    internet: 'Internet',
    internetOffline: 'Not required',
    internetOptional: 'Only for optional Quran audio',
    platform: 'Platform',
    platformValue: 'Android (phone & tablet)',
    screenshots: 'Screenshots',
    privacyBoxTitle: 'Privacy at a glance',
    privacyBoxText: 'No personal data is collected or shared. No ads, no analytics, no tracking, no accounts.',
    otherApps: 'More apps',
    sourceCode: 'Source code',
    backHome: 'All apps',
    notFound: 'Page not found',
    notFoundText: 'This page does not exist. Go back to the overview of all apps.',
  },
  de: {
    siteName: 'Islamische Lern-Apps',
    metaDescription: 'Vier kostenlose islamische Lern-Apps für Kinder, Jugendliche und Erwachsene – ohne Werbung, ohne Tracking, offline und quellenbasiert. Auf Deutsch, Englisch und Bosnisch.',
    nav: { apps: 'Apps', principles: 'Grundsätze', faq: 'FAQ', contact: 'Kontakt' },
    heroKicker: 'Kostenlos · Ohne Werbung · Offline',
    heroTitle: 'Den Islam mit Freude lernen – verlässlich und privat',
    heroText: 'Vier kostenlose Lern-Apps für Kinder, Jugendliche und Erwachsene: vom ersten Gebet und den Geschichten der Propheten bis zum Leben des Propheten Muhammad ﷺ. Keine Werbung, keine Käufe, kein Tracking – und jede Lektion nennt ihre Quellen.',
    heroCta: 'Die Apps entdecken',
    appsTitle: 'Die Apps',
    appsText: 'Jede App ist für ein anderes Alter und eine andere Art zu lernen gemacht. Alle gibt es auf Deutsch, Englisch und Bosnisch.',
    more: 'Mehr erfahren',
    principlesTitle: 'Was alle vier Apps gemeinsam haben',
    principles: [
      ['Komplett kostenlos', 'Keine Werbung, keine In-App-Käufe, keine Abos und kein Pay-to-Win.'],
      ['Privat von Grund auf', 'Keine Konten, keine Analyse, kein Tracking. Der Fortschritt bleibt auf deinem Gerät.'],
      ['Funktioniert offline', 'Alle Inhalte sind in der App – ideal für Reisen, Schule und Familienzeit.'],
      ['Quellenbasiert', 'Koran- und Hadith-Belege für jede Lektion. Nichts ist erfunden; Meinungsunterschiede der Gelehrten werden genannt.'],
      ['Respektvoll', 'Propheten werden nie dargestellt. Die Bilder zeigen nur Landschaften, Gebäude und Gegenstände.'],
      ['Barrierearm', 'Drei Sprachen, größere Schrift, hoher Kontrast, reduzierte Bewegung und Screenreader-Unterstützung.'],
    ],
    parentsTitle: 'Für Eltern, Lehrkräfte und Moscheegemeinden',
    parentsText: 'Die Apps sind Lernbegleiter – sie unterstützen das Lernen in der Familie, den islamischen Religionsunterricht und Wochenendschulen, ersetzen aber weder Eltern noch Lehrkräfte oder Imame und erteilen keine Fatwas. Kinder können die Kinder-Apps sicher nutzen: Es gibt keine Werbung, keine Chats, keine Links zu sozialen Netzwerken und keine Datenerhebung.',
    shareTitle: 'Teile die Apps',
    shareText: 'Die Apps sind kostenlos und bleiben kostenlos. Am meisten hilfst du, wenn du diese Seite mit Familien, Lehrkräften und deiner Moscheegemeinde teilst.',
    copyLink: 'Link kopieren',
    copied: 'Link kopiert',
    faqTitle: 'Häufige Fragen',
    faq: [
      ['Sind die Apps wirklich kostenlos?', 'Ja. Es gibt keine Werbung, keine Käufe und keine Abos – jetzt und in Zukunft.'],
      ['Brauchen die Apps Internet?', 'Nein. Alle vier Apps funktionieren offline. Nur Islam Quest lädt Audio aus dem Internet, wenn du eine Koranrezitation anhören möchtest.'],
      ['Welche Sprachen gibt es?', 'Deutsch, Englisch und Bosnisch. Die Sprache kannst du jederzeit in der App wechseln.'],
      ['Wie wird sichergestellt, dass die Inhalte stimmen?', 'Jede Lektion nennt ihre Quellen (Koran sowie anerkannte Hadith- und Sira-Werke). Der Korantext stammt aus dem geprüften Tanzil-Text und wird nie von Hand abgetippt. Nichts ist erfunden, und wo Gelehrte unterschiedliche gültige Ansichten vertreten, sagt die App das. Wenn du einen Fehler findest, schreib uns bitte – Korrekturen sind willkommen.'],
      ['Werden Propheten bildlich dargestellt?', 'Nein. Propheten werden nie dargestellt. Personen erscheinen in Sira nur als Schrift.'],
      ['Welche Geräte werden unterstützt?', 'Android-Smartphones und -Tablets über Google Play.'],
      ['Welche Daten erheben die Apps?', 'Keine. Der Fortschritt wird nur auf deinem Gerät gespeichert und kann jederzeit in den Einstellungen gelöscht werden. Siehe die Datenschutzerklärung der jeweiligen App.'],
    ],
    contactTitle: 'Kontakt',
    contactText: 'Fragen, Feedback oder eine inhaltliche Korrektur? Wir freuen uns über deine Nachricht.',
    footerNote: 'Kostenlose islamische Lern-Apps von Certi Development.',
    privacy: 'Datenschutz',
    imprint: 'Impressum',
    appPrivacy: 'Datenschutzerklärung der App',
    language: 'Sprache',
    getOnPlay: 'Jetzt bei Google Play',
    comingSoon: 'Bald bei Google Play',
    forWhom: 'Für',
    languages: 'Sprachen',
    languagesValue: 'Deutsch, Englisch, Bosnisch',
    price: 'Preis',
    priceValue: 'Kostenlos – ohne Werbung, ohne Käufe',
    internet: 'Internet',
    internetOffline: 'Nicht nötig',
    internetOptional: 'Nur für optionales Koran-Audio',
    platform: 'Plattform',
    platformValue: 'Android (Smartphone & Tablet)',
    screenshots: 'Screenshots',
    privacyBoxTitle: 'Datenschutz auf einen Blick',
    privacyBoxText: 'Es werden keine personenbezogenen Daten erhoben oder weitergegeben. Keine Werbung, keine Analyse, kein Tracking, keine Konten.',
    otherApps: 'Weitere Apps',
    sourceCode: 'Quellcode',
    backHome: 'Alle Apps',
    notFound: 'Seite nicht gefunden',
    notFoundText: 'Diese Seite gibt es nicht. Zurück zur Übersicht aller Apps.',
  },
  bs: {
    siteName: 'Islamske aplikacije za učenje',
    metaDescription: 'Četiri besplatne islamske aplikacije za učenje za djecu, mlade i odrasle – bez reklama, bez praćenja, offline i zasnovane na izvorima. Na bosanskom, njemačkom i engleskom.',
    nav: { apps: 'Aplikacije', principles: 'Principi', faq: 'Pitanja', contact: 'Kontakt' },
    heroKicker: 'Besplatno · Bez reklama · Offline',
    heroTitle: 'Uči islam s radošću – pouzdano i privatno',
    heroText: 'Četiri besplatne aplikacije za učenje za djecu, mlade i odrasle: od prvog namaza i priča o poslanicima do života Poslanika Muhammeda ﷺ. Bez reklama, bez kupovina, bez praćenja – a svaka lekcija navodi svoje izvore.',
    heroCta: 'Otkrij aplikacije',
    appsTitle: 'Aplikacije',
    appsText: 'Svaka aplikacija je napravljena za drugi uzrast i drugi način učenja. Sve su dostupne na bosanskom, njemačkom i engleskom.',
    more: 'Saznaj više',
    principlesTitle: 'Šta je zajedničko svim četirima aplikacijama',
    principles: [
      ['Potpuno besplatno', 'Bez reklama, bez kupovina u aplikaciji, bez pretplata i bez plaćanja za prednost.'],
      ['Privatnost od početka', 'Bez korisničkih računa, analitike i praćenja. Napredak ostaje na tvom uređaju.'],
      ['Radi offline', 'Sav sadržaj je u aplikaciji – idealno za putovanja, školu i porodično vrijeme.'],
      ['Zasnovano na izvorima', 'Izvori iz Kur’ana i hadisa za svaku lekciju. Ništa nije izmišljeno; razlike među učenjacima su navedene.'],
      ['S poštovanjem', 'Poslanici se nikad ne prikazuju. Ilustracije pokazuju samo pejzaže, građevine i predmete.'],
      ['Pristupačno', 'Tri jezika, veći tekst, visok kontrast, smanjeno kretanje i podrška za čitač ekrana.'],
    ],
    parentsTitle: 'Za roditelje, učitelje i džematske zajednice',
    parentsText: 'Aplikacije su pratioci u učenju – podržavaju učenje u porodici, vjeronauku i mekteb, ali ne zamjenjuju roditelje, učitelje ni imame i ne daju fetve. Djeca mogu sigurno koristiti dječije aplikacije: nema reklama, chatova, linkova na društvene mreže ni prikupljanja podataka.',
    shareTitle: 'Podijeli aplikacije',
    shareText: 'Aplikacije su besplatne i ostat će besplatne. Najviše pomažeš ako podijeliš ovu stranicu s porodicama, učiteljima i svojim džematom.',
    copyLink: 'Kopiraj link',
    copied: 'Link kopiran',
    faqTitle: 'Česta pitanja',
    faq: [
      ['Jesu li aplikacije zaista besplatne?', 'Da. Nema reklama, kupovina ni pretplata – ni sada ni u budućnosti.'],
      ['Trebaju li aplikacije internet?', 'Ne. Sve četiri aplikacije rade offline. Samo Islam Quest učitava zvuk s interneta kada želiš poslušati učenje Kur’ana.'],
      ['Koji jezici su podržani?', 'Bosanski, njemački i engleski. Jezik možeš promijeniti u aplikaciji u svakom trenutku.'],
      ['Kako se osigurava tačnost sadržaja?', 'Svaka lekcija navodi svoje izvore (Kur’an te priznata djela hadisa i Sire). Tekst Kur’ana preuzet je iz provjerenog Tanzil teksta i nikad se ne prepisuje ručno. Ništa nije izmišljeno, a gdje učenjaci imaju različita valjana mišljenja, aplikacija to kaže. Ako pronađeš grešku, piši nam – ispravke su dobrodošle.'],
      ['Prikazuju li se poslanici na slikama?', 'Ne. Poslanici se nikad ne prikazuju. Ljudi su u Siri predstavljeni samo pismom.'],
      ['Koji uređaji su podržani?', 'Android telefoni i tableti putem Google Playa.'],
      ['Koje podatke aplikacije prikupljaju?', 'Nikakve. Napredak se čuva samo na tvom uređaju i može se izbrisati u postavkama u svakom trenutku. Pogledaj politiku privatnosti svake aplikacije.'],
    ],
    contactTitle: 'Kontakt',
    contactText: 'Pitanja, povratne informacije ili ispravka sadržaja? Radujemo se tvojoj poruci.',
    footerNote: 'Besplatne islamske aplikacije za učenje – Certi Development.',
    privacy: 'Privatnost',
    imprint: 'Impressum',
    appPrivacy: 'Politika privatnosti aplikacije',
    language: 'Jezik',
    getOnPlay: 'Preuzmi na Google Playu',
    comingSoon: 'Uskoro na Google Playu',
    forWhom: 'Za',
    languages: 'Jezici',
    languagesValue: 'Bosanski, njemački, engleski',
    price: 'Cijena',
    priceValue: 'Besplatno – bez reklama i kupovina',
    internet: 'Internet',
    internetOffline: 'Nije potreban',
    internetOptional: 'Samo za neobavezni audio Kur’ana',
    platform: 'Platforma',
    platformValue: 'Android (telefon i tablet)',
    screenshots: 'Snimci ekrana',
    privacyBoxTitle: 'Privatnost ukratko',
    privacyBoxText: 'Ne prikupljaju se niti dijele lični podaci. Bez reklama, analitike, praćenja i korisničkih računa.',
    otherApps: 'Druge aplikacije',
    sourceCode: 'Izvorni kod',
    backHome: 'Sve aplikacije',
    notFound: 'Stranica nije pronađena',
    notFoundText: 'Ova stranica ne postoji. Vrati se na pregled svih aplikacija.',
  },
};

/* Privacy policy for each app. */
export const APP_PRIVACY = {
  en: {
    title: 'Privacy policy',
    updated: 'Last updated',
    intro: (n) => `${n} is a free educational app by ${SITE.owner} (${SITE.brand}). This policy explains how the app handles information.`,
    h1: 'Summary',
    summary: 'The app does not collect, transmit, sell or share any personal data. There are no ads, no analytics, no tracking, no accounts and no in-app purchases.',
    h2: 'Data stored on your device',
    stored: (s) => `The app stores ${s} only on your device. This data never leaves your device. You can delete it at any time with “Reset progress” in the settings, or by uninstalling the app.`,
    h3: 'Internet use',
    offline: 'The app works fully offline and does not send any data over the internet.',
    links: 'Some source references contain links to quran.com or sunnah.com. They open only when you tap them, in your browser; the privacy policies of those websites then apply.',
    h4: 'Notifications',
    reminders: 'If you switch on reminders, the app schedules local notifications on your device. No server is involved. You can switch them off in the app or in your device settings at any time.',
    h5: 'Children',
    children: 'The app is suitable for children. Because it collects no personal data, no personal data of children is collected either.',
    h6: 'Google Play',
    play: 'When you download the app from Google Play, Google processes data according to its own privacy policy. We do not receive any personal data about you from this.',
    h7: 'Permissions',
    permissions: (r) => (r ? 'The app only asks for permission to show notifications, and only if you switch on reminders.' : 'The app does not request any special permissions.'),
    h8: 'Changes',
    changes: 'If this policy changes, the new version will be published on this page with a new date.',
    h9: 'Contact',
    contact: 'Responsible for this app and contact for privacy questions:',
  },
  de: {
    title: 'Datenschutzerklärung',
    updated: 'Zuletzt aktualisiert',
    intro: (n) => `${n} ist eine kostenlose Lern-App von ${SITE.owner} (${SITE.brand}). Diese Erklärung beschreibt, wie die App mit Informationen umgeht.`,
    h1: 'Zusammenfassung',
    summary: 'Die App erhebt, überträgt, verkauft oder teilt keine personenbezogenen Daten. Es gibt keine Werbung, keine Analyse, kein Tracking, keine Konten und keine In-App-Käufe.',
    h2: 'Daten auf deinem Gerät',
    stored: (s) => `Die App speichert ${s} ausschließlich auf deinem Gerät. Diese Daten verlassen dein Gerät nie. Du kannst sie jederzeit mit „Fortschritt zurücksetzen“ in den Einstellungen oder durch Deinstallieren der App löschen.`,
    h3: 'Internetnutzung',
    offline: 'Die App funktioniert vollständig offline und sendet keine Daten über das Internet.',
    links: 'Einige Quellenangaben enthalten Links zu quran.com oder sunnah.com. Sie öffnen sich nur, wenn du sie antippst, in deinem Browser; dann gelten die Datenschutzerklärungen dieser Websites.',
    h4: 'Benachrichtigungen',
    reminders: 'Wenn du Erinnerungen einschaltest, plant die App lokale Benachrichtigungen auf deinem Gerät. Dabei ist kein Server beteiligt. Du kannst sie jederzeit in der App oder in den Geräteeinstellungen ausschalten.',
    h5: 'Kinder',
    children: 'Die App ist für Kinder geeignet. Da sie keine personenbezogenen Daten erhebt, werden auch keine Daten von Kindern erhoben.',
    h6: 'Google Play',
    play: 'Wenn du die App über Google Play herunterlädst, verarbeitet Google Daten nach seiner eigenen Datenschutzerklärung. Wir erhalten dadurch keine personenbezogenen Daten über dich.',
    h7: 'Berechtigungen',
    permissions: (r) => (r ? 'Die App fragt nur nach der Berechtigung, Benachrichtigungen anzuzeigen – und nur, wenn du Erinnerungen einschaltest.' : 'Die App fordert keine besonderen Berechtigungen an.'),
    h8: 'Änderungen',
    changes: 'Wenn sich diese Erklärung ändert, wird die neue Fassung mit neuem Datum auf dieser Seite veröffentlicht.',
    h9: 'Kontakt',
    contact: 'Verantwortlich für diese App und Ansprechpartner für Datenschutzfragen:',
  },
  bs: {
    title: 'Politika privatnosti',
    updated: 'Posljednje ažuriranje',
    intro: (n) => `${n} je besplatna edukativna aplikacija koju je izradio ${SITE.owner} (${SITE.brand}). Ova politika objašnjava kako aplikacija postupa s podacima.`,
    h1: 'Ukratko',
    summary: 'Aplikacija ne prikuplja, ne prenosi, ne prodaje i ne dijeli nikakve lične podatke. Nema reklama, analitike, praćenja, korisničkih računa ni kupovina u aplikaciji.',
    h2: 'Podaci na tvom uređaju',
    stored: (s) => `Aplikacija čuva ${s} isključivo na tvom uređaju. Ti podaci nikad ne napuštaju tvoj uređaj. Možeš ih izbrisati u svakom trenutku opcijom „Poništi napredak“ u postavkama ili deinstaliranjem aplikacije.`,
    h3: 'Korištenje interneta',
    offline: 'Aplikacija radi potpuno bez interneta i ne šalje nikakve podatke putem interneta.',
    links: 'Neki izvori sadrže linkove na quran.com ili sunnah.com. Otvaraju se samo kada ih dodirneš, u tvom pregledniku; tada važe politike privatnosti tih stranica.',
    h4: 'Obavještenja',
    reminders: 'Ako uključiš podsjetnike, aplikacija zakazuje lokalna obavještenja na tvom uređaju. Pri tome nije uključen nikakav server. Možeš ih isključiti u aplikaciji ili u postavkama uređaja u svakom trenutku.',
    h5: 'Djeca',
    children: 'Aplikacija je prikladna za djecu. Budući da ne prikuplja lične podatke, ne prikuplja ni podatke djece.',
    h6: 'Google Play',
    play: 'Kada preuzmeš aplikaciju s Google Playa, Google obrađuje podatke prema svojoj politici privatnosti. Mi time ne dobivamo nikakve lične podatke o tebi.',
    h7: 'Dozvole',
    permissions: (r) => (r ? 'Aplikacija traži samo dozvolu za prikaz obavještenja – i to samo ako uključiš podsjetnike.' : 'Aplikacija ne traži nikakve posebne dozvole.'),
    h8: 'Izmjene',
    changes: 'Ako se ova politika promijeni, nova verzija bit će objavljena na ovoj stranici s novim datumom.',
    h9: 'Kontakt',
    contact: 'Odgovorna osoba za ovu aplikaciju i kontakt za pitanja o privatnosti:',
  },
};

/* Website privacy policy (Datenschutzerklärung). Sections are [heading, paragraphs[]]. */
export const SITE_PRIVACY = {
  en: {
    title: 'Privacy policy',
    sections: [
      ['1. Controller', ['__CONTROLLER__']],
      ['2. Overview', ['This website presents our free learning apps. It uses no cookies, no analytics, no advertising, no social media plugins and no external fonts or scripts. All files are loaded from the same server.']],
      ['3. Hosting on GitHub Pages', [
        'This website is hosted by GitHub Pages, a service of GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. When you visit the website, GitHub automatically processes technical access data (server log files), in particular your IP address, the date and time of access, the page requested and browser information. This is necessary to deliver the website securely and to defend against attacks.',
        'Legal basis is Art. 6(1)(f) GDPR; our legitimate interest is the secure and reliable provision of this website. Data may be transferred to the USA. GitHub states that it participates in the EU–U.S. Data Privacy Framework; transfers are therefore based on an adequacy decision of the European Commission (Art. 45 GDPR). We have no access to these log files. More information: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">GitHub Privacy Statement</a>.',
      ]],
      ['4. Contact by email', ['If you write to us by email, we process your email address and the content of your message only to answer your request. Legal basis is Art. 6(1)(b) GDPR (if your request relates to a contract) or Art. 6(1)(f) GDPR (our legitimate interest in answering enquiries). We delete the data when it is no longer needed, unless statutory retention obligations apply.']],
      ['5. Links to Google Play and GitHub', ['Links to Google Play and GitHub are ordinary links. Data is only transferred to these services when you click such a link; their privacy policies then apply.']],
      ['6. Our apps', ['Our apps do not collect any personal data. Details are described in the privacy policy of each app:', '__APP_LINKS__']],
      ['7. Your rights', [
        'You have the right to access (Art. 15 GDPR), rectification (Art. 16), erasure (Art. 17), restriction of processing (Art. 18), data portability (Art. 20) and to object to processing based on Art. 6(1)(f) GDPR (Art. 21). To exercise your rights, simply contact us by email.',
        'You also have the right to lodge a complaint with a data protection supervisory authority, for example the authority responsible for us: Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Kavalleriestraße 2–4, 40213 Düsseldorf, Germany.',
      ]],
      ['8. Changes', ['We update this privacy policy when the website or legal requirements change. The current version is always available on this page.']],
    ],
  },
  de: {
    title: 'Datenschutzerklärung',
    sections: [
      ['1. Verantwortlicher', ['__CONTROLLER__']],
      ['2. Überblick', ['Diese Website stellt unsere kostenlosen Lern-Apps vor. Sie verwendet keine Cookies, keine Analyse-Tools, keine Werbung, keine Social-Media-Plugins und keine externen Schriftarten oder Skripte. Alle Dateien werden vom selben Server geladen.']],
      ['3. Hosting über GitHub Pages', [
        'Diese Website wird über GitHub Pages bereitgestellt, einen Dienst der GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, USA. Beim Aufruf der Website verarbeitet GitHub automatisch technische Zugriffsdaten (Server-Logfiles), insbesondere deine IP-Adresse, Datum und Uhrzeit des Zugriffs, die aufgerufene Seite und Browser-Informationen. Dies ist erforderlich, um die Website sicher auszuliefern und Angriffe abzuwehren.',
        'Rechtsgrundlage ist Art. 6 Abs. 1 lit. f DSGVO; unser berechtigtes Interesse liegt in der sicheren und zuverlässigen Bereitstellung dieser Website. Dabei können Daten in die USA übermittelt werden. GitHub gibt an, am EU-U.S. Data Privacy Framework teilzunehmen; die Übermittlung erfolgt daher auf Grundlage eines Angemessenheitsbeschlusses der Europäischen Kommission (Art. 45 DSGVO). Wir selbst haben keinen Zugriff auf diese Logfiles. Weitere Informationen: <a href="https://docs.github.com/de/site-policy/privacy-policies/github-general-privacy-statement">Datenschutzerklärung von GitHub</a>.',
      ]],
      ['4. Kontakt per E-Mail', ['Wenn du uns per E-Mail schreibst, verarbeiten wir deine E-Mail-Adresse und den Inhalt deiner Nachricht ausschließlich zur Beantwortung deiner Anfrage. Rechtsgrundlage ist Art. 6 Abs. 1 lit. b DSGVO (sofern deine Anfrage auf einen Vertrag gerichtet ist) bzw. Art. 6 Abs. 1 lit. f DSGVO (unser berechtigtes Interesse an der Beantwortung von Anfragen). Wir löschen die Daten, sobald sie nicht mehr erforderlich sind, sofern keine gesetzlichen Aufbewahrungspflichten bestehen.']],
      ['5. Links zu Google Play und GitHub', ['Links zu Google Play und GitHub sind einfache Verlinkungen. Daten werden erst an diese Dienste übertragen, wenn du einen solchen Link anklickst; dann gelten deren Datenschutzerklärungen.']],
      ['6. Unsere Apps', ['Unsere Apps erheben keine personenbezogenen Daten. Die Einzelheiten stehen in der Datenschutzerklärung der jeweiligen App:', '__APP_LINKS__']],
      ['7. Deine Rechte', [
        'Du hast das Recht auf Auskunft (Art. 15 DSGVO), Berichtigung (Art. 16 DSGVO), Löschung (Art. 17 DSGVO), Einschränkung der Verarbeitung (Art. 18 DSGVO), Datenübertragbarkeit (Art. 20 DSGVO) sowie auf Widerspruch gegen Verarbeitungen auf Grundlage von Art. 6 Abs. 1 lit. f DSGVO (Art. 21 DSGVO). Zur Ausübung deiner Rechte genügt eine E-Mail an uns.',
        'Außerdem hast du das Recht, dich bei einer Datenschutz-Aufsichtsbehörde zu beschweren, zum Beispiel bei der für uns zuständigen Behörde: Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Kavalleriestraße 2–4, 40213 Düsseldorf.',
      ]],
      ['8. Änderungen', ['Wir passen diese Datenschutzerklärung an, wenn sich die Website oder die rechtlichen Vorgaben ändern. Die aktuelle Fassung findest du immer auf dieser Seite.']],
    ],
  },
  bs: {
    title: 'Politika privatnosti',
    sections: [
      ['1. Odgovorna osoba', ['__CONTROLLER__']],
      ['2. Pregled', ['Ova web stranica predstavlja naše besplatne aplikacije za učenje. Ne koristi kolačiće (cookies), analitiku, reklame, dodatke društvenih mreža ni vanjske fontove ili skripte. Sve datoteke se učitavaju s istog servera.']],
      ['3. Hosting na GitHub Pages', [
        'Ova web stranica se nalazi na GitHub Pages, usluzi kompanije GitHub, Inc., 88 Colin P. Kelly Jr. Street, San Francisco, CA 94107, SAD. Kada posjetiš stranicu, GitHub automatski obrađuje tehničke podatke o pristupu (log datoteke servera), posebno tvoju IP adresu, datum i vrijeme pristupa, traženu stranicu i podatke o pregledniku. To je potrebno za sigurnu isporuku stranice i odbranu od napada.',
        'Pravni osnov je član 6. stav 1. tačka f) GDPR-a; naš legitimni interes je sigurno i pouzdano pružanje ove stranice. Podaci se mogu prenijeti u SAD. GitHub navodi da učestvuje u okviru EU–U.S. Data Privacy Framework; prijenos se stoga zasniva na odluci Evropske komisije o adekvatnosti (član 45. GDPR-a). Mi nemamo pristup ovim log datotekama. Više informacija: <a href="https://docs.github.com/en/site-policy/privacy-policies/github-general-privacy-statement">Izjava o privatnosti GitHuba</a>.',
      ]],
      ['4. Kontakt putem e-maila', ['Ako nam pišeš e-mailom, tvoju e-mail adresu i sadržaj poruke obrađujemo isključivo da bismo odgovorili na tvoj upit. Pravni osnov je član 6. stav 1. tačka b) GDPR-a (ako se upit odnosi na ugovor) odnosno tačka f) (naš legitimni interes da odgovaramo na upite). Podatke brišemo čim više nisu potrebni, osim ako postoje zakonske obaveze čuvanja.']],
      ['5. Linkovi na Google Play i GitHub', ['Linkovi na Google Play i GitHub su obični linkovi. Podaci se prenose tim uslugama tek kada klikneš na takav link; tada važe njihove politike privatnosti.']],
      ['6. Naše aplikacije', ['Naše aplikacije ne prikupljaju nikakve lične podatke. Detalji su opisani u politici privatnosti svake aplikacije:', '__APP_LINKS__']],
      ['7. Tvoja prava', [
        'Imaš pravo na pristup (član 15. GDPR-a), ispravku (član 16.), brisanje (član 17.), ograničenje obrade (član 18.), prenosivost podataka (član 20.) te pravo na prigovor obradi zasnovanoj na članu 6. stav 1. tačka f) (član 21.). Za ostvarivanje svojih prava dovoljno je da nam pošalješ e-mail.',
        'Također imaš pravo podnijeti pritužbu nadzornom tijelu za zaštitu podataka, na primjer tijelu nadležnom za nas: Landesbeauftragte für Datenschutz und Informationsfreiheit Nordrhein-Westfalen (LDI NRW), Kavalleriestraße 2–4, 40213 Düsseldorf, Njemačka.',
      ]],
      ['8. Izmjene', ['Ovu politiku privatnosti ažuriramo kada se promijene stranica ili zakonski zahtjevi. Aktuelna verzija je uvijek dostupna na ovoj stranici.']],
    ],
  },
};

/* Imprint (Impressum, § 5 DDG). */
export const IMPRINT = {
  en: {
    title: 'Imprint',
    provider: 'Information according to § 5 DDG (German Digital Services Act)',
    contact: 'Contact',
    responsible: 'Responsible for content according to § 18(2) MStV',
    disclaimerTitle: 'Liability for content and links',
    disclaimer: 'We create the content of this website and of our apps with great care, including the religious content, which is based on the sources cited. Nevertheless, we cannot guarantee that it is complete and free of errors; the apps are learning companions and do not replace religious advice from qualified scholars. We are not responsible for the content of external websites linked from here; at the time of linking, no legal violations were recognisable.',
    disputeTitle: 'Consumer dispute resolution',
    dispute: 'We are neither obliged nor willing to participate in dispute resolution proceedings before a consumer arbitration board.',
  },
  de: {
    title: 'Impressum',
    provider: 'Angaben gemäß § 5 DDG',
    contact: 'Kontakt',
    responsible: 'Verantwortlich für den Inhalt nach § 18 Abs. 2 MStV',
    disclaimerTitle: 'Haftung für Inhalte und Links',
    disclaimer: 'Die Inhalte dieser Website und unserer Apps erstellen wir mit größter Sorgfalt, auch die religiösen Inhalte, die auf den angegebenen Quellen beruhen. Für Vollständigkeit und Fehlerfreiheit können wir dennoch keine Gewähr übernehmen; die Apps sind Lernbegleiter und ersetzen keine religiöse Beratung durch qualifizierte Gelehrte. Für die Inhalte verlinkter externer Websites sind wir nicht verantwortlich; zum Zeitpunkt der Verlinkung waren keine Rechtsverstöße erkennbar.',
    disputeTitle: 'Verbraucherstreitbeilegung',
    dispute: 'Wir sind nicht bereit oder verpflichtet, an Streitbeilegungsverfahren vor einer Verbraucherschlichtungsstelle teilzunehmen.',
  },
  bs: {
    title: 'Impressum',
    provider: 'Podaci prema § 5 DDG (njemački Zakon o digitalnim uslugama)',
    contact: 'Kontakt',
    responsible: 'Odgovoran za sadržaj prema § 18 st. 2 MStV',
    disclaimerTitle: 'Odgovornost za sadržaj i linkove',
    disclaimer: 'Sadržaj ove stranice i naših aplikacija izrađujemo s najvećom pažnjom, uključujući vjerski sadržaj koji se zasniva na navedenim izvorima. Ipak, ne možemo garantovati potpunost i tačnost bez greške; aplikacije su pratioci u učenju i ne zamjenjuju vjerski savjet kvalifikovanih učenjaka. Nismo odgovorni za sadržaj vanjskih stranica na koje upućujemo; u trenutku postavljanja linka nisu bila uočljiva kršenja zakona.',
    disputeTitle: 'Rješavanje potrošačkih sporova',
    dispute: 'Nismo spremni niti obavezni učestvovati u postupcima rješavanja sporova pred tijelom za potrošačku arbitražu.',
  },
};

